
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.coobird.thumbnailator.Thumbnails;
import net.proteanit.sql.DbUtils;


public class StudentProfile extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form StudentInfo
     */
    public StudentProfile() {
        initComponents();
        
        // Creating a connection from your database to a java program
        conn = MySQLConnect.ConnectDB();
        radio_btn_3.setSelected(false);
        radio_btn_3.setVisible(false);
        // showing data in JTable upon execution
        updateTable();
    }
    
    // Method for emptying all fields
    public void clearFields(){
        txtField_student_id.setText("");
        txtField_fname.setText("");
        txtField_mname.setText("");
        txtField_lname.setText("");
        radio_btn_male.setSelected(false);
        radio_btn_female.setSelected(false);
        radio_btn_3.setSelected(true);
        dc_birthdate.setDate(null);
        txtField_contact_number.setText("");
        txtField_address.setText("");
        label_image.setIcon(null);
        txtField_image_path.setText("");
        dc_date_enrolled.setDate(null);
        txtField_course_id.setText("");
    }
    
    private void updateTable(){
        
        try {
            
            String sql = "SELECT * FROM stud_profile";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_student_info.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } finally {
            
            try {
                // Closing the connection
                rs.close();
                pst.close();
            } catch (Exception e){
                
            }
            
        } // end of finally block
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtField_contact_number = new javax.swing.JTextField();
        txtField_student_id = new javax.swing.JTextField();
        txtField_mname = new javax.swing.JTextField();
        txtField_fname = new javax.swing.JTextField();
        txtField_image_path = new javax.swing.JTextField();
        radio_btn_male = new javax.swing.JRadioButton();
        radio_btn_female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtField_address = new javax.swing.JTextArea();
        btn_upload_image = new javax.swing.JButton();
        txtField_course_id = new javax.swing.JTextField();
        txtField_lname = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        label_image = new javax.swing.JLabel();
        dc_birthdate = new com.toedter.calendar.JDateChooser();
        dc_date_enrolled = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        radio_btn_3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_student_info = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Student ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Middle Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Sex");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Birthdate");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Contact Number");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Image path");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Course ID");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Date Enrolled");

        txtField_contact_number.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_contact_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_contact_numberActionPerformed(evt);
            }
        });

        txtField_student_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_student_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_student_idActionPerformed(evt);
            }
        });

        txtField_mname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_mnameActionPerformed(evt);
            }
        });

        txtField_fname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_fnameActionPerformed(evt);
            }
        });

        txtField_image_path.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_image_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_image_pathActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_btn_male);
        radio_btn_male.setText("Male");
        radio_btn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_btn_female);
        radio_btn_female.setText("Female");
        radio_btn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_femaleActionPerformed(evt);
            }
        });

        txtField_address.setColumns(20);
        txtField_address.setRows(5);
        jScrollPane1.setViewportView(txtField_address);

        btn_upload_image.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_upload_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image upload.png"))); // NOI18N
        btn_upload_image.setText("Upload Image");
        btn_upload_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upload_imageActionPerformed(evt);
            }
        });

        txtField_course_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_course_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_course_idActionPerformed(evt);
            }
        });

        txtField_lname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_lnameActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));

        label_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jDesktopPane1.setLayer(label_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        dc_birthdate.setDateFormatString("yyyy,MM,dd");

        dc_date_enrolled.setDateFormatString("yyyy,MM,dd");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(txtField_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(radio_btn_male)
                            .addGap(27, 27, 27)
                            .addComponent(radio_btn_female, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtField_lname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtField_mname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_student_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_upload_image, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dc_date_enrolled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtField_course_id, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtField_student_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtField_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jScrollPane1))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btn_upload_image, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(txtField_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio_btn_male)
                            .addComponent(radio_btn_female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel11))
                            .addComponent(dc_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_date_enrolled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtField_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtField_course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDesktopPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_new.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_update.setText("Update");

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_clear.setText("Clear");

        jLabel13.setText("Search");

        buttonGroup1.add(radio_btn_3);
        radio_btn_3.setText("rb3");
        radio_btn_3.setBorderPainted(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update)
                .addGap(12, 12, 12)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_btn_3)
                .addGap(64, 64, 64))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio_btn_3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(jTextField3))
                            .addComponent(btn_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);

        table_student_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_student_info.setRequestFocusEnabled(false);
        table_student_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_student_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_student_info);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_student_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_student_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_student_idActionPerformed

    private void txtField_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_mnameActionPerformed

    private void txtField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_fnameActionPerformed

    private void txtField_image_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_image_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_image_pathActionPerformed

    private void txtField_course_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_course_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_course_idActionPerformed

    private void txtField_contact_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_contact_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_contact_numberActionPerformed

    private void txtField_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_lnameActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_upload_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upload_imageActionPerformed
        // JFileChooser pops up after clicking UploadImage button
        JFileChooser chooser = new JFileChooser();
        // Setting JFileChooser to null when it's opened to make sure nothing is selected
        chooser.showOpenDialog(null);
        // Getting the SelectedFile from the FileChooser and put inside this File f object
        File f = chooser.getSelectedFile();
        // Getting the Absolute pathname (String) of the Selected File into filename 
        filename = f.getAbsolutePath();
        // Displaying the Absolute pathname of the file in JTextField image path
        txtField_image_path.setText(filename);
        
        // Writing Code for Uploading Image
        try{
            // Creating a new object of File called image and passing the filename into the image variable of File
            File image = new File(filename);
            
            // BufferedImage used to manipulate the image data and using Thumbnails.of() method 
            // File image. size(dimension ranging from 0-255).creates a thumbnail and returns a BufferedImage()
            // Thanks to the Thumbnailator jar file we can upload an image with different dimensions by setting a specific size ranging from 0 - 255
            BufferedImage thumbnail = Thumbnails.of(image).size(180, 220).asBufferedImage();
            
            // Creating Buffer inside the memory 
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            
            // Writes an image using an artbitrary image writer passing 3 parameters (BufferedImage, format, ByteArrayOutputStream)
            ImageIO.write(thumbnail, "jpeg", os);
            
            // When the Buffered is inside the memory it allows us to receive the data 
            InputStream is = new ByteArrayInputStream(os.toByteArray());
            
            // Creating a new object ByteArrayOutputStream into the memory 
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            // The object of byte[1024] is = 1 megabyte.
            // meaning the image memory is 1 megabyte.
            byte[] buf = new byte[1024];
            
            // Reads the next byte of data from the InputStream and returns int in the range of 0 to 255
            // If no byte is available because of the end of the stream has been reached, returns -1
            for(int readNum; (readNum = is.read(buf)) != -1;){
                // Writes the image into the JPanel
                // Writes the length of bytes from the specified byte array to this output stream buf.
                bos.write(buf, 0, readNum);
            }
            
            // Passing the object "thumbnail" of BufferedImage into the ImageIcon
            viewImage = new ImageIcon(thumbnail);
            // Displaying the icon viewImage into the JLabel_image
            label_image.setIcon(viewImage);
            
            // Creating from OutputStream the image from JLabel into this studentImage
            studentImage = bos.toByteArray();
            
                    
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_upload_imageActionPerformed

    private void radio_btn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_maleActionPerformed
       sex = "Male";
    }//GEN-LAST:event_radio_btn_maleActionPerformed

    private void radio_btn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_femaleActionPerformed
        sex ="Female"; 
    }//GEN-LAST:event_radio_btn_femaleActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // Writing code for data input validation
        String firstName_validate = txtField_fname.getText();
        String mname_validate = txtField_mname.getText();
        String lname_validate = txtField_lname.getText();
        
        Date date_bd = dc_birthdate.getDate();
        String cn_validate = txtField_contact_number.getText();
        String address_validate = txtField_address.getText();
        
        Date date_dateEnrolled = dc_date_enrolled.getDate();
        String courseID_validate = txtField_course_id.getText();
        
        // Using if-else conditions for validation
        if(firstName_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your first name");
        } else if(mname_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your middle name");
        } else if(lname_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your last name");
        } else if (sex == null){
            JOptionPane.showMessageDialog(null, "Please select your sex: Male or Female");
        } else if (date_bd == null){
            JOptionPane.showMessageDialog(null, "Please select your birthdate");
        } else if (cn_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your contact number");
        } else if (address_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your address");
        } else if (studentImage == null){
            JOptionPane.showMessageDialog(null, "Please choose an image");
        } else if (date_dateEnrolled == null){
            JOptionPane.showMessageDialog(null, "Please select your date of enrollment");
        } else if (courseID_validate == null){
            JOptionPane.showMessageDialog(null, "Please enter your course ID");
        }
        else {
           
        // If all data validations have been assigned a value then run 
        try {
            // Writing SQL query and storing in sql String variable
            String sql = "INSERT INTO stud_profile (fname, mname, lname, sex, birthdate, contact_number, address, course_id, date_enrolled, stud_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
            // Oject conn is used to create connection between java application and MySQL database and will execute the query
            pst = conn.prepareStatement(sql);
            
            // Getting data to INSERT INTO the database
            pst.setString(1, txtField_fname.getText());
            pst.setString(2, txtField_mname.getText());
            pst.setString(3, txtField_lname.getText());
            pst.setString(4, sex);
            
            // Taking an object of Date from java utility package and getting the date from JDateChooseer birthdate 
            java.util.Date date_birthdate = dc_birthdate.getDate();
            // Giving format for the date using SimpleDateFormat Class by taking an object named sdf 
            SimpleDateFormat sdf_birthdate = new SimpleDateFormat("yyyy-MM-dd");
            // Storing the date format in strDateOutput String variable
            String strBirthDate = sdf_birthdate.format(date_birthdate);
            
            pst.setString(5, strBirthDate);
            pst.setString(6, txtField_contact_number.getText());
            pst.setString(7, txtField_address.getText());
            
            String courseID = txtField_course_id.getText();
            //String courseID_data = Integer.parseInt(courseID);
            
            pst.setString(8, courseID);
            ;
            
             // Taking an object of Date from java utility package and getting the date from JDateChooseer birthdate 
            java.util.Date date_enrolled = dc_date_enrolled.getDate();
            // Giving format for the date using SimpleDateFormat Class by taking an object named sdf 
            SimpleDateFormat sdf_date_enrolled = new SimpleDateFormat("yyyy-MM-dd");
            // Storing the date format in strDateOutput String variable
            String strDateEnrolled = sdf_date_enrolled.format(date_enrolled);
            
            pst.setString(9, strDateEnrolled);
            pst.setBytes(10, studentImage);
            
            // execute() method used to execute the SQL query
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully!");
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        } finally {
            try {
                // Closing the connection in both ResultSet and PreparedStatement
                rs.close();
                pst.close();
            } catch (Exception e){
                
            }
        } // end of finally block
        } // end of else block
        
        // Updating data in JTable after saving 
        updateTable();
        // Clearing all the fields after saving
        clearFields();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // Calling clearFields method upon clicking New Button
        clearFields();
    }//GEN-LAST:event_btn_newActionPerformed

    private void table_student_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_student_infoMouseClicked
        
        int row = table_student_info.getSelectedRow();
        String tableClick = table_student_info.getModel().getValueAt(row, 0).toString();
        
        try {
            
            String sql = "SELECT * FROM stud_profile WHERE stud_id = " + tableClick;
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()){
                String str_fname = rs.getString("fname");
                txtField_fname.setText(str_fname);
                
                String str_mname = rs.getString("mname");
                txtField_mname.setText(str_mname);
                
                String str_lname = rs.getString("lname");
                txtField_lname.setText(str_lname);
                
                String str_sex = rs.getString("sex");
                if ("Male".equals(str_sex)){
                    radio_btn_male.setSelected(true);
                }
                
                if ("Female".equals("sex")){
                    radio_btn_female.setSelected(true);
                }     
                
            }
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_table_student_infoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_upload_image;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dc_birthdate;
    private com.toedter.calendar.JDateChooser dc_date_enrolled;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel label_image;
    private javax.swing.JRadioButton radio_btn_3;
    private javax.swing.JRadioButton radio_btn_female;
    private javax.swing.JRadioButton radio_btn_male;
    private javax.swing.JTable table_student_info;
    private javax.swing.JTextArea txtField_address;
    private javax.swing.JTextField txtField_contact_number;
    private javax.swing.JTextField txtField_course_id;
    private javax.swing.JTextField txtField_fname;
    private javax.swing.JTextField txtField_image_path;
    private javax.swing.JTextField txtField_lname;
    private javax.swing.JTextField txtField_mname;
    private javax.swing.JTextField txtField_student_id;
    // End of variables declaration//GEN-END:variables
String filename = null;
private ImageIcon viewImage = null;
private String sex; 
byte[] studentImage = null;
}

