
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;


public class Subject extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form StudentInfo
     */
    public Subject() {
        initComponents();
        
        // Creating a connection from your database to a java program
        conn = MySQLConnect.ConnectDB();
        // showing data in JTable upon execution
        updateTable();
        btn_save.setEnabled(false);
    }
    
    // Method for emptying all fields
    public void clearFields(){
        txtField_subject_id.setText("");
        txtField_subject_desc.setText("");
        txtField_units.setText("");
        cb_schedule.setSelectedIndex(-1);
        txtField_room.setText("");
        txtField_instructor.setText("");
    }
    
    private void updateTable(){
        
        try {
            
            String sql = "SELECT * FROM subject";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_subject_info.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } finally {
            
            try {
                // Closing the connection
                rs.close();
                pst.close();
            } catch (Exception e){
                
            }
            
        } // end of finally block
    } // end of update method
    
        // Creating a method for Close Operation
    public void close(){
        WindowEvent wce = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wce);
        
    } // end of close method
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtField_room = new javax.swing.JTextField();
        txtField_subject_id = new javax.swing.JTextField();
        txtField_units = new javax.swing.JTextField();
        txtField_subject_desc = new javax.swing.JTextField();
        cb_schedule = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtField_instructor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txtField_search = new javax.swing.JTextField();
        btn_print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_subject_info = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Subject ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Subject Description");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Units");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Schedule");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Room");

        txtField_room.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_roomActionPerformed(evt);
            }
        });

        txtField_subject_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_subject_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_subject_idActionPerformed(evt);
            }
        });

        txtField_units.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_unitsActionPerformed(evt);
            }
        });

        txtField_subject_desc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_subject_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_subject_descActionPerformed(evt);
            }
        });

        cb_schedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_schedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00:00", "08:00:00", "09:00:00", "10:00:00", "11:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Instructor");

        txtField_instructor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_subject_desc, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtField_subject_id)
                    .addComponent(txtField_units)
                    .addComponent(txtField_room, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtField_instructor)
                    .addComponent(cb_schedule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtField_subject_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_subject_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_units, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtField_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtField_instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_new.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        txtField_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_searchActionPerformed(evt);
            }
        });
        txtField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtField_searchKeyReleased(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update)
                .addGap(12, 12, 12)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_print)
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(txtField_search))
                                .addComponent(btn_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_print, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);

        table_subject_info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_subject_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_subject_info.setGridColor(new java.awt.Color(0, 153, 51));
        table_subject_info.setRequestFocusEnabled(false);
        table_subject_info.setSelectionBackground(new java.awt.Color(102, 102, 102));
        table_subject_info.setSelectionForeground(new java.awt.Color(102, 255, 255));
        table_subject_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_subject_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_subject_info);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // Checks if there is any selected data to be deleted 
        if (txtField_subject_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please select data to delete");
        } else {
            // Creating a confirmDialog for confirming data deletion
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this data?","Delete",JOptionPane.YES_NO_OPTION);
            
            // p = 0 means yes / p = -1 means no
            if (p == 0){
              try {
                  // MySQL query for deleting single record / row 
                  String sql = "DELETE FROM subject WHERE subj_id = ?";
                  pst = conn.prepareStatement(sql);
                  pst.setString(1, txtField_subject_id.getText());
                  pst.execute();
                  // Display this message after successfully running DELETE query
                  JOptionPane.showMessageDialog(null, "Data deleted successfully!");
                  
              } catch (Exception e){
                  JOptionPane.showMessageDialog(null, e);
              } finally {
                  try{
                      // Closing the connection
                      rs.close();
                      pst.close();
                  } catch (Exception e){
                      
                  }
              } // end of finally block
            } 
        } // end of else statement
            clearFields();
            updateTable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // Writing code for data input validation
        String subj_id_validate = txtField_subject_id.getText();
        String subjectDesc_validate = txtField_subject_desc.getText();
        String units_validate = txtField_units.getText();
        String room_validate = txtField_room.getText();
        String instructor_validate = txtField_instructor.getText();
      
        // Using if-else conditions for validation
        if (subj_id_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your subject id");
        } else if(subjectDesc_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the subject description");
        } else if(units_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the number of units");
        } else if(cb_schedule.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please enter select the schedule");
        } else if (room_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the room");
        } else if (instructor_validate.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter the name of the Instructor");
        }
        
        else {
           
        // If all data validations have been assigned a value then run 
        try {
            // Writing SQL query and storing in sql String variable
            String sql = "INSERT INTO subject (subj_id, subj_desc, units, schedule, room, instructor) VALUES (?, ?, ?, ?, ?, ?);";
            // Oject conn is used to create connection between java application and MySQL database and will execute the query
            pst = conn.prepareStatement(sql);
            
            // Getting data to INSERT INTO the database
            pst.setString(1, txtField_subject_id.getText());
            pst.setString(2, txtField_subject_desc.getText());
            pst.setString(3, txtField_units.getText());
            
            String schedule_value = cb_schedule.getSelectedItem().toString();
            pst.setString(4, schedule_value);
            
            pst.setString(5, txtField_room.getText());
            pst.setString(6, txtField_instructor.getText());
            
            // execute() method used to execute the SQL query
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully!");
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        } finally {
            try {
                // Closing the connection in both ResultSet and PreparedStatement
                rs.close();
                pst.close();
            } catch (Exception e){
                
            }
        } // end of finally block
        } // end of else block
        
        // Updating data in JTable after saving 
        updateTable();
        // Clearing all the fields after saving
        clearFields();
        
        // Button Settings
        btn_save.setEnabled(false);
        btn_new.setEnabled(true);
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_clear.setEnabled(true);
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // Calling clearFields method upon clicking New Button
        clearFields();
        
        // Button Settings
        btn_save.setEnabled(true);
        btn_new.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_clear.setEnabled(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void table_subject_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_subject_infoMouseClicked
        
        int row = table_subject_info.getSelectedRow();
        String tableClick = (table_subject_info.getModel().getValueAt(row, 0).toString());
        
        try {
            
            String sql = "SELECT * FROM subject WHERE subj_id = " + tableClick;
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()){
                String str_subjID = rs.getString("subj_id");
                txtField_subject_id.setText(str_subjID);
                
                String str_subj_desc = rs.getString("subj_desc");
                txtField_subject_desc.setText(str_subj_desc);
                
                String str_units = rs.getString("units");
                txtField_units.setText(str_units);
                
                String str_schedule = rs.getString("schedule");
                cb_schedule.setSelectedItem(str_schedule);
                
                String str_room = rs.getString("room");
                txtField_room.setText(str_room);   
                
                String str_instructor = rs.getString("instructor");
                txtField_instructor.setText(str_instructor);
                  
            } // end if rs.next() method
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e){
                
            }
            
        }
        
        // Button Settings
        btn_save.setEnabled(false);
        btn_new.setEnabled(true);
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_clear.setEnabled(true);
    }//GEN-LAST:event_table_subject_infoMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        try {
            String sql = "UPDATE subject SET subj_desc = ?, units = ?, schedule = ?, room = ?, instructor =? WHERE subj_id = ?";
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtField_subject_desc.getText());
            pst.setString(2, txtField_units.getText());
            
            String schedule_value = cb_schedule.getSelectedItem().toString();
            pst.setString(3, schedule_value);
            
            pst.setString(4, txtField_room.getText());
            pst.setString(5, txtField_instructor.getText());
            pst.setString(6, txtField_subject_id.getText());
            
            // execute() method used to execute the SQL query
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully!");
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                // Closing the connection
                pst.close();
                rs.close();
            } catch (Exception e){
                
            }
            
        } // end of finally block
        updateTable();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // Calling clear method for clearing data
        clearFields();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        
        // Header Format name
        MessageFormat header = new MessageFormat("Student Enrollment Form Print");
        
        // Footer Format
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try {
            // Basic syntax for printing JTable directly
            table_subject_info.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (java.awt.print.PrinterException e){
            // Display error message if cannot be printed out
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void txtField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_searchActionPerformed
        
        
    }//GEN-LAST:event_txtField_searchActionPerformed

    private void txtField_subject_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_subject_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_subject_descActionPerformed

    private void txtField_unitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_unitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_unitsActionPerformed

    private void txtField_subject_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_subject_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_subject_idActionPerformed

    private void txtField_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_roomActionPerformed

    private void txtField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField_searchKeyReleased
        String search_validate = txtField_search.getText();
       
       if (search_validate.equals("")){
           updateTable();
       } else {
        
         try {
             String sql = "SELECT * FROM subject WHERE subj_id = ?"; 
             pst = conn.prepareStatement(sql);
             pst.setString(1, txtField_search.getText());
             rs = pst.executeQuery();
             
             table_subject_info.setModel(DbUtils.resultSetToTableModel(rs));
             
             pst.close();
             
         } catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
        
       }
    }//GEN-LAST:event_txtField_searchKeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StudentProfile stud_profile = new StudentProfile();
        stud_profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_schedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_subject_info;
    private javax.swing.JTextField txtField_instructor;
    private javax.swing.JTextField txtField_room;
    private javax.swing.JTextField txtField_search;
    private javax.swing.JTextField txtField_subject_desc;
    private javax.swing.JTextField txtField_subject_id;
    private javax.swing.JTextField txtField_units;
    // End of variables declaration//GEN-END:variables

}

